### ISSUE TITLE
Green screen crash when attempting to boot in Nintendont

### ISSUE THREAD

**Issue by BashPrime** [aprilwade/randomprime#5]
randomprime version: v0.2.0
Nintendont version used: v5.480
Metroid Prime 0-00 MD5: eeacd0ced8e2bae491eca14f141a4b7c
Layout descriptor: Any (from what I've tested)

I apologize in advance for the issue being vague, but patched Metroid Prime games run into a green screen crash when attempting to load in Nintendont.

I started to notice the issue in Nintendont v5.480. Rolling back to v5.460 or v4.447 (versions that Interslice and I use, respectively) is a currently known solution. I am not currently sure which Nintendont update broke compatibility with randomprime generated games.

I have not attempted running a randomprime game with Dios Mios. I have no known issues running with any Dolphin 5 version.

**Comment by BashPrime** [comment]
After testing with various Nintendont versions, I can confirm that the crash begins with [Nintendont version 5.477](https://github.com/FIX94/Nintendont/commit/f5a27ba76b5eaa0d22c27bbe76c900728ab1168d).

**Comment by aprilwade** [comment]
I believe I have this figured out.  The crash occurs when any Pak file in the
ISO contains 0 resources, which happens when the flag to skip the frigate level
is given.  When that flag is set, the contents of Metroid1.pak (the Pak that
contains the resources for the frigate level) are not copied to the output ISO
in order make writing it faster.  So, I've implemented a simple workaround:
stick a small dummy resource in Metroid1.pak instead.  It's inelegant, but it
works.  See commit 38c23241bb83f77fb9a452fb03a1ac98317c5867


I'll release 0.2.1 with this fix shortly.

More details for the curious: I believe the crash is cause by a bug in
nintendont (introduced in 5.477 as mentioned above).  A bit of background: In
order to save space in main memory (MRAM), Metroid Prime stores metadata about
the contents of the Pak files in the DSP's memory ARAM, only copying parts of
it to MRAM when necessary.  Nintendont's implementation for the DMA transfer
request appears to crash when a length of 0 is given.  So, when a pak contains
0 resources, the table containing its metadata is empty, and a DMA transfer
with length 0 made.

**Comment by BashPrime** [comment]
Thank you so much! Interesting how Nintendont doesn't like 0-length transfers very much.
